//
//  CMVHelpShift.m
//  Casinò di Venezia
//
//  Created by Massimo Moro on 28/10/14.
//  Copyright (c) 2014 Casinò di Venezia SPA. All rights reserved.
//

#import "CMVHelpShift.h"

@implementation CMVHelpShift


// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
- (void)drawRect:(CGRect)rect {
    
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    
    //// Frames
    CGRect frame = rect;
    
    //// Subframes
    CGRect shape_ = CGRectMake(CGRectGetMinX(frame) + 4, CGRectGetMinY(frame) + 1, CGRectGetWidth(frame) - 6, CGRectGetHeight(frame) - 5);
    
    
    //// Shape_69
    {
    }
    
    
    //// Shape_
    {
        //// Bezier 2 Drawing
        UIBezierPath* bezier2Path = [UIBezierPath bezierPath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.56909 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.83429 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.57818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.86000 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.56727 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.84286 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.57091 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.85714 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.68545 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.88286 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.61091 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.87429 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.64727 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.88286 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.72909 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.87429 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.70000 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.88286 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.71455 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.87714 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.74000 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.87143 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.73273 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.87429 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.73636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.87143 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.92000 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.99714 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.80000 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.98000 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.87818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.99714 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.94909 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.99429 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.93636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.99714 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.94727 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.99429 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.96000 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.97714 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.95455 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.99143 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.96000 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.98571 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.95091 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.95143 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.96000 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.96286 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.95636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.95429 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.88182 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.83714 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.89818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.91143 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.88545 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.86000 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.88182 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.80286 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.87818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.81714 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.88182 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.80286 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.99818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.51714 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.95636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.73429 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.99818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.63143 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.68364 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.15143 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.99818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.31143 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.86000 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.15143 * CGRectGetHeight(shape_))];
        [bezier2Path addLineToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.68182 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.15143 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.66909 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.17429 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.67455 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.15143 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.66727 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.16571 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.71273 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.54857 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.71273 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.30857 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.73455 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.41714 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.56909 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.83429 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.68545 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.72571 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.57636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.80857 * CGRectGetHeight(shape_))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.69818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.43714 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.36909 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.01429 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.69818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.18857 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.56364 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.01429 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.00545 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.43714 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.16545 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.01429 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.00545 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.20000 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.14000 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.76571 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.00545 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.56857 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.05455 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.68857 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.14182 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.80571 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.14182 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.76857 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.14545 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.78286 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.06000 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.94571 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.13818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.83143 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.12545 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.89714 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.05273 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.96857 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.05455 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.94857 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.05091 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.96000 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.06364 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.98571 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.05273 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.97714 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.05818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.98571 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.09636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.98857 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.06364 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.98571 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.07636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.98857 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.30727 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.84286 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.14545 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.98857 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.23818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.96857 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.32182 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.84857 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.31273 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.84286 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.31636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.84571 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.37091 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.85714 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.33818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.85429 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.35455 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.85714 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.69818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.43714 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.56364 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.85714 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.69818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.68571 * CGRectGetHeight(shape_))];
        [bezier2Path closePath];
        [bezier2Path moveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.37091 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.81429 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.32727 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.80571 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.35636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.81429 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.34182 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.80857 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.30364 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.80000 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.32000 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.80286 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.31091 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.80000 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.29091 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.80857 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.29818 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.80000 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.29455 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.80286 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.11455 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.94857 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.23636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.91714 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.16182 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.94286 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.17273 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.79714 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.16545 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.88857 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.17091 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.82000 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.15636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.73143 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.17273 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.76571 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.16727 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.74286 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.03636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.44000 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.08000 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.66000 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.03636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.55429 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.37273 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.06000 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.03636 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.23143 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.18727 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.06000 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.67455 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.44000 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.55091 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.06000 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.67455 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.21714 * CGRectGetHeight(shape_))];
        [bezier2Path addCurveToPoint: CGPointMake(CGRectGetMinX(shape_) + 0.37091 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.81429 * CGRectGetHeight(shape_)) controlPoint1: CGPointMake(CGRectGetMinX(shape_) + 0.67091 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.66000 * CGRectGetHeight(shape_)) controlPoint2: CGPointMake(CGRectGetMinX(shape_) + 0.54727 * CGRectGetWidth(shape_), CGRectGetMinY(shape_) + 0.81429 * CGRectGetHeight(shape_))];
        [bezier2Path closePath];
        bezier2Path.miterLimit = 4;
        
        [color setFill];
        [bezier2Path fill];
    }
}


@end
