//
//  CMVLocker.m
//  Casinò di Venezia
//
//  Created by Massimo Moro on 10/03/14.
//  Copyright (c) 2014 Casinò di Venezia SPA. All rights reserved.
//

#import "CMVLocker.h"

@implementation CMVLocker
@synthesize selected = _selected;

- (id)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        // Initialization code
    }
    return self;
}


// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
- (void)drawRect:(CGRect)rect
{
    //// Frames
    CGRect frame = rect;
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 0.9];
    
    if (_selected) {
        [[NSUserDefaults standardUserDefaults] setObject:@0 forKey:@"Locked"];
        [[NSUserDefaults standardUserDefaults] synchronize];
    
        _selected=!_selected;
    
    
    //// Livello 1 Drawing
    UIBezierPath* livello1Path = [UIBezierPath bezierPath];
    [livello1Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.86036 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98230 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.40738 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98230 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70937 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98230 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55837 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98230 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39912 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97864 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.40463 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98106 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.40197 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97945 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31899 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87183 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.35110 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96511 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31948 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92460 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31900 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58849 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31812 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77739 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31784 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68292 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41292 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47824 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31974 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52875 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.35785 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48584 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42273 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47567 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.41642 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47776 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.41982 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47645 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42205 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29521 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.42273 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41463 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.42505 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35477 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32562 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19617 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.41934 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24157 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.37530 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19945 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21652 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28219 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.27446 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19280 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.22760 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.22921 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21294 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32564 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.21357 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29627 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.21306 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31113 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21278 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47530 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.21252 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37530 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.21278 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42497 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10788 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47530 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.17623 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47530 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.14206 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47530 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10788 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28368 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.10788 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41143 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.10788 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34755 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.11089 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27447 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.10891 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28061 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.11040 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27763 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.22018 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11139 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.12245 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20113 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.15847 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14557 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.29507 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08407 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.24333 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09856 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.27000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09296 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34373 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08407 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31129 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08407 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32751 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08407 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.35033 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08727 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.34593 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08516 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.34802 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08683 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52819 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31108 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.45723 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10745 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52761 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19589 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52823 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42070 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52837 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34762 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52822 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38416 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52823 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47784 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52823 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43906 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52823 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45741 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47784 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.53737 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47784 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.54407 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47784 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84234 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47797 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64796 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47786 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74515 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47773 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.94704 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56434 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.89559 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47810 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.93291 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50923 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95021 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57111 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.94765 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56672 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.94913 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56886 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95021 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88649 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.95021 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67624 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.95021 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78136 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.86036 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98230 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.93863 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93801 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.90877 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97006 * CGRectGetHeight(frame))];
    [livello1Path closePath];
    [livello1Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60728 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79717 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60742 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83706 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60728 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81047 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60666 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82381 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63506 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87035 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60865 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85861 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61921 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87077 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66132 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83566 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65045 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86995 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66102 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85638 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66126 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76982 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66165 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81371 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66177 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79175 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67234 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73851 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66097 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75748 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66291 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74812 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67166 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66183 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69338 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71707 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.69201 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68302 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59757 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66136 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65088 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64020 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61783 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63999 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59655 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74014 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.57655 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68354 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.57683 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71615 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60687 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76731 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60230 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74713 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60516 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75782 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60728 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79717 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60860 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77694 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60725 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78719 * CGRectGetHeight(frame))];
    [livello1Path closePath];
    [color setFill];
        [livello1Path fill];
    } else {
        
        [[NSUserDefaults standardUserDefaults] setObject:@1 forKey:@"Locked"];
        [[NSUserDefaults standardUserDefaults] synchronize];
        _selected=!_selected;
        //// Livello Drawing
        UIBezierPath* livelloPath = [UIBezierPath bezierPath];
        [livelloPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60520 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79495 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60534 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83485 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60520 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80825 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60458 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82160 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63299 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86814 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60658 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85640 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61713 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86856 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65925 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83345 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64837 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86774 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.65894 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85417 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65919 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76760 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65958 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81150 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.65970 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78954 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67026 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73630 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65890 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75527 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66083 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74591 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66959 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65962 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69130 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71486 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68994 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68081 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59550 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65915 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64881 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63799 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61575 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63777 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59447 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73793 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.57448 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68133 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.57476 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71393 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60479 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76510 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60022 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74492 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60309 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75560 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60520 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79495 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60652 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77473 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60518 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78498 * CGRectGetHeight(frame))];
        [livelloPath closePath];
        [livelloPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84025 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47566 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.94496 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56212 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.89349 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47579 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.93083 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50702 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.94813 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56890 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.94558 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56451 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.94706 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56665 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.94813 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88428 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.94813 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67402 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.94813 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77915 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.85828 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98009 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.93655 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93580 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.90670 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96784 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.40530 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98009 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70729 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98009 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55630 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98009 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39704 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97643 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.40255 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97885 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39990 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97723 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86962 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.34903 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96290 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31740 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92239 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31693 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58627 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31605 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77518 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31577 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68071 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41084 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47603 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31767 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52653 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.35578 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48363 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41701 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47309 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.41434 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47555 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.41561 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47468 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41701 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28147 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.41701 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40921 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.41701 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34534 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42002 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27226 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.41804 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27840 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.41952 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27542 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52931 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10917 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.43158 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19892 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.46760 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14335 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60420 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08186 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.55246 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09635 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.57913 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09075 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65286 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08186 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.62042 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08186 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.63664 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08186 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65945 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08505 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65506 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08295 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.65715 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08462 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.83731 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30887 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.76636 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10523 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.83674 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19367 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.83736 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41849 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.83750 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34541 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.83735 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38195 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.83736 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47563 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.83736 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43684 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.83736 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45520 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84025 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47566 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.84650 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47563 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.84090 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47587 * CGRectGetHeight(frame))];
        [livelloPath closePath];
        [livelloPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.73186 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47346 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.73118 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29299 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.73186 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41242 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.73418 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35256 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63475 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19396 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72847 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23936 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68443 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19723 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52564 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27998 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.58359 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19058 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.53673 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.22700 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52207 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32343 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52270 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29406 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52219 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30891 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52191 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47309 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52165 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37309 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52191 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42276 * CGRectGetHeight(frame))];
        [livelloPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.73186 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47346 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52247 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47325 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.73161 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47381 * CGRectGetHeight(frame))];
        [livelloPath closePath];
        [color setFill];
        [livelloPath fill];

    }
}


@end
