//
//  CMVPhoneInfo.m
//  Casinò di Venezia
//
//  Created by Massimo Moro on 12/03/14.
//  Copyright (c) 2014 Casinò di Venezia SPA. All rights reserved.
//

#import "CMVPhoneInfo.h"

@implementation CMVPhoneInfo

- (id)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        // Initialization code
    }
    return self;
}


// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
- (void)drawRect:(CGRect)rect
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 0.718];
    UIColor* color2 = [UIColor colorWithRed: 0 green: 0 blue: 0 alpha: 0.81];
    
    //// Frames
    CGRect frame = rect;
    
    
    //// Abstracted Attributes
    NSString* textContent = @"INFO";
    
    
    //// Rounded Rectangle Drawing
    UIBezierPath* roundedRectanglePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(CGRectGetMinX(frame) + 1.5, CGRectGetMinY(frame) + 1.5, CGRectGetWidth(frame) - 2.5, CGRectGetHeight(frame) - 3) cornerRadius: 3.5];
    [color setFill];
    [roundedRectanglePath fill];
    
    
    //// Livello 1 Drawing
    UIBezierPath* livello1Path = [UIBezierPath bezierPath];
    [livello1Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65410 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47417 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67080 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53343 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65513 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50662 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66055 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52616 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69012 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53660 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.67718 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53795 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68365 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53777 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.71111 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52225 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69734 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53528 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.70443 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53154 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.72930 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44519 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72192 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50723 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.72818 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48171 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.72969 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39958 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72977 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43009 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.72950 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41478 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.73971 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35060 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72998 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37740 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.73324 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36071 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.74603 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34270 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.74173 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34744 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74387 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34482 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.77442 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32871 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.75526 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33369 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.76480 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33022 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82383 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33474 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.79095 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32613 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.80745 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32628 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84456 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35612 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.83109 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33848 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.83812 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34452 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.85023 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38253 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.84791 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36214 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.84999 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37068 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.85081 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43380 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.85057 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39960 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.85075 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41671 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.87199 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52602 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.85098 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47919 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.85817 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51147 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.90902 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53334 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.88407 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53874 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.89650 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54063 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.92577 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48059 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.91847 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52783 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.92423 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51000 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.92514 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39148 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.92733 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45086 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.92707 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42102 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.91094 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28245 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.92260 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35247 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.91731 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31678 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.90730 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27265 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.91006 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27774 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.90895 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27466 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.85922 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23059 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.89172 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25368 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.87566 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24008 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.78952 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21214 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.83618 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21729 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.81293 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21197 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.72238 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.22946 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.76438 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21217 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74650 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.21649 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67288 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27272 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70541 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23858 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68889 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25293 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66941 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28229 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.67130 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27468 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.67015 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27756 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66332 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32069 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66740 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29511 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66525 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.30775 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65410 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47417 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65606 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36942 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.65238 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42021 * CGRectGetHeight(frame))];
    [livello1Path closePath];
    [livello1Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68401 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80901 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68667 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81788 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.68400 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81400 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68512 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81690 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68851 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81813 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.68726 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81825 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68789 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81813 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.89183 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81813 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.75628 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81814 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.82405 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81814 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.89312 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81810 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.89226 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81813 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.89269 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81818 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.89653 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80718 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.89530 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81771 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.89654 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81398 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.89637 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71755 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.89651 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77730 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.89653 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74742 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.88960 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64956 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.89623 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69298 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.89472 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66953 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.88521 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63118 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.88807 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64360 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.88676 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63708 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84737 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48776 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.87262 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58331 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.86001 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53550 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84605 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47646 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.84646 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48432 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.84603 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48096 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84608 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41135 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.84611 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45476 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.84608 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43305 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84152 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39737 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.84607 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40078 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.84497 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39738 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.81210 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39737 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.83171 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39735 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.82191 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39735 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.80769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41116 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.80882 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39738 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.80769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40093 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.80769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45938 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.80769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42711 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.80769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44307 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.77282 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45938 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.79604 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45938 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.78454 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45938 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.77282 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45298 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.77282 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45706 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.77282 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45502 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.77281 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41129 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.77282 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43909 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.77282 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42519 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76841 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39737 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.77281 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40109 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.77165 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39738 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.73881 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39738 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.75854 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39735 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74868 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39735 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.73443 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41077 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.73563 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39738 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.73443 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40108 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.73439 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47815 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.73442 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43323 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.73446 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45569 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.73343 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48626 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.73438 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48089 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.73399 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48411 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.72275 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52640 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72992 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49977 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.72630 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51299 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69509 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63135 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.71351 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56132 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.70418 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.59603 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68433 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71540 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.68879 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65585 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68469 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68370 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68401 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80901 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.68397 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74658 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68405 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77781 * CGRectGetHeight(frame))];
    [livello1Path closePath];
    [color2 setFill];
    [livello1Path fill];
    
    
    //// Text Drawing
    CGRect textRect = CGRectMake(CGRectGetMinX(frame)-10, CGRectGetMinY(frame)+3, CGRectGetWidth(frame), CGRectGetHeight(frame));
    [[UIColor blackColor] setFill];
    [textContent drawInRect: textRect withFont: [UIFont fontWithName: @"Avenir" size: 9] lineBreakMode: NSLineBreakByWordWrapping alignment: NSTextAlignmentCenter];
}


@end
