//
//  CMVLock.m
//  Casinò di Venezia
//
//  Created by Massimo Moro on 10/03/14.
//  Copyright (c) 2014 Casinò di Venezia SPA. All rights reserved.
//

#import "CMVLock.h"

@implementation CMVLock

- (id)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        // Initialization code
    }
    return self;
}

// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
- (void)drawRect:(CGRect)rect
{
    //// Color Declarations
    UIColor* color = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    
    //// Frames
    CGRect frame = rect;
    
    
    //// Livello 1 Drawing
    UIBezierPath* livello1Path = [UIBezierPath bezierPath];
    [livello1Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.86036 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98230 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.40738 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98230 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70937 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98230 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55837 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98230 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39912 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97864 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.40463 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98106 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.40197 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97945 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31899 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87183 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.35110 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96511 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31948 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92460 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31900 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58849 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31812 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77739 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31784 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68292 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41292 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47824 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31974 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52875 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.35785 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48584 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42273 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47567 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.41642 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47776 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.41982 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47645 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42205 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29521 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.42273 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41463 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.42505 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35477 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32562 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19617 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.41934 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24157 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.37530 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19945 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21652 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28219 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.27446 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19280 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.22760 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.22921 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21294 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32564 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.21357 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.29627 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.21306 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31113 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.21278 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47530 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.21252 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37530 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.21278 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42497 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10788 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47530 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.17623 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47530 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.14206 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47530 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10788 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28368 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.10788 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41143 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.10788 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34755 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.11089 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27447 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.10891 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.28061 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.11040 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.27763 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.22018 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11139 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.12245 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.20113 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.15847 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14557 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.29507 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08407 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.24333 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09856 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.27000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09296 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34373 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08407 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31129 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08407 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32751 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08407 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.35033 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08727 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.34593 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08516 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.34802 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08683 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52819 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31108 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.45723 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10745 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52761 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19589 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52823 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42070 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52837 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34762 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52822 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38416 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.52823 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47784 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52823 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43906 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.52823 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45741 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47784 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.53737 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47784 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.54407 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47784 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84234 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47797 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64796 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47786 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74515 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47773 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.94704 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56434 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.89559 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47810 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.93291 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50923 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95021 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57111 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.94765 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56672 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.94913 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56886 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.95021 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88649 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.95021 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67624 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.95021 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78136 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.86036 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98230 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.93863 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93801 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.90877 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97006 * CGRectGetHeight(frame))];
    [livello1Path closePath];
    [livello1Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60728 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79717 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60742 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83706 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60728 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81047 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60666 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82381 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63506 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87035 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60865 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85861 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61921 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87077 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66132 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83566 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65045 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86995 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66102 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85638 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66126 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76982 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66165 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81371 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66177 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79175 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67234 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73851 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66097 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75748 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66291 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74812 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67166 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66183 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69338 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71707 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.69201 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68302 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59757 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66136 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65088 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64020 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61783 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63999 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59655 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74014 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.57655 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68354 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.57683 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71615 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60687 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76731 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60230 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74713 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60516 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.75782 * CGRectGetHeight(frame))];
    [livello1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60728 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79717 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60860 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77694 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60725 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78719 * CGRectGetHeight(frame))];
    [livello1Path closePath];
    [color setFill];
    [livello1Path fill];
}


@end
