//
//  CMVSubscription.m
//  Casinò di Venezia
//
//  Created by Massimo Moro on 17/10/14.
//  Copyright (c) 2014 Casinò di Venezia SPA. All rights reserved.
//

#import "CMVSubscription.h"

@implementation CMVSubscription


// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
- (void)drawRect:(CGRect)rect {
    //// Color Declarations
    UIColor *color=[[UIColor alloc] init];
    //// Color Declarations
    if (!self.highlitedColor) {
        color = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 1];
    } else {
        color = self.highlitedColor;
    }
    
    //// Frames
    CGRect frame =rect;
    
    
    //// Group
    {
    }
    
    
    //// Bezier 4 Drawing
    UIBezierPath* bezier4Path = [UIBezierPath bezierPath];
    [bezier4Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95385 * CGRectGetHeight(frame))];
    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.16462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95385 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.09077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.12462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95385 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.09077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92000 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.10462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80154 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.09077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87846 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.09231 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84769 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.35385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67077 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.11846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74615 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.23846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70462 * CGRectGetHeight(frame))];
    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66615 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39231 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58615 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.37846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66308 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63231 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.35846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54615 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57692 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.36923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56308 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53231 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.35538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54154 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.35231 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53692 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47846 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.33846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51538 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50000 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.29538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45692 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.31077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47538 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.30154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46769 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.27385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34462 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.27692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42154 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.26615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36615 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.29385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32462 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.27692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33538 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.28462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32769 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.16000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.29385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24308 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19077 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15077 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.34923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15692 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.34923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15385 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.40923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10769 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.35692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12308 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11077 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09231 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.40923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10308 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.41077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09692 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.05846 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.41846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08000 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.43077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06154 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.45692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06154 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.05692 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.45231 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.05846 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.46308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.07231 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.46000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06462 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.46308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06769 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.48769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08615 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.46462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.07385 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.47231 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08154 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.56462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11231 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09538 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.54923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10615 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32615 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14308 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.22308 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.70615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34462 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32923 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.70308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33538 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45692 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.71385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36615 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.70308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.42154 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47692 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.68000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46615 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.67077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47385 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53231 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50000 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.64308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51538 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.62462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54769 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.63077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53692 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.62769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54154 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58615 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.61538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56462 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57692 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66769 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62769 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66308 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69231 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67692 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68462 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.88154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80154 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.77846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71846 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.86769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74615 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.89538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.89385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.84923 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.89538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86308 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95385 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.89538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92000 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.86308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95385 * CGRectGetHeight(frame))];
    [bezier4Path closePath];
    [bezier4Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35385 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.30462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35538 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.30615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35385 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.30462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35538 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44308 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.30154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36615 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.30769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41231 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.33385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45077 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.32769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44769 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.33231 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45077 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.34769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.46154 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.34000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45077 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.34615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45538 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51846 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.35538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48462 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.36615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50000 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53385 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52308 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52769 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57077 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55077 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.40615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56308 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58308 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.42308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57385 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.42462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57846 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.37846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69846 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.42308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61385 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.41692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68769 * CGRectGetHeight(frame))];
    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70308 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.13385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81077 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.21846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74462 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.14154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78154 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.12154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88154 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.12308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85385 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.12154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88154 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.16462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92308 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.12154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90462 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.14154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92308 * CGRectGetHeight(frame))];
    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.82154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92308 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.86462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.88000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.84462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92308 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.86462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90308 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.85077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80923 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.86462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86769 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.86308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85692 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.72154 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.84154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.77077 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.75385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.74308 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69538 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71231 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.62923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70462 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.56462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57846 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.57077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68154 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.56462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61538 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.57077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56615 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.56462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57385 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.56615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56923 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53077 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.58000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55846 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.58923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54769 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51538 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52462 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52000 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.63846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45846 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.62000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49846 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.63077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48154 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.65077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44923 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.45385 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.64462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44923 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44154 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.65231 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44923 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.65692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44615 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.68000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35385 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.67692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41077 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.68308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.36462 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.67538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35231 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.68000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35385 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.67846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35231 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34769 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.67077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35231 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35077 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.66000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33692 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34462 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.66000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34000 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.66308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24000 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.62615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.16769 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.48308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11385 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.54000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13385 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.51538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12308 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09692 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.47231 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11077 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.45846 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10462 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10769 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10000 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.44462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.10462 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11231 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11077 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.44462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11231 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.44462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12923 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11692 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.44769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12462 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.43077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13692 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44154 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13385 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.43692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13692 * CGRectGetHeight(frame))];
    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.42923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13692 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39231 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14615 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.42615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13692 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.40462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.13692 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.39385 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14769 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39231 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14615 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39231 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14769 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38923 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.16615 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.15385 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.39538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.16154 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.33692 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.36000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.19231 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32462 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.24308 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.32308 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34769 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.32769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34154 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.32615 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34462 * CGRectGetHeight(frame))];
    [bezier4Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35385 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.32000 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35231 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.31538 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35385 * CGRectGetHeight(frame))];
    [bezier4Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.31077 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.35385 * CGRectGetHeight(frame))];
    [bezier4Path closePath];
    bezier4Path.miterLimit = 4;
    
    [color setFill];
    [bezier4Path fill];
    self.highlitedColor=nil;
}


@end
