//
//  CMVVoiceOpen.m
//  Casinò di Venezia
//
//  Created by Massimo Moro on 05/03/14.
//  Copyright (c) 2014 Casinò di Venezia SPA. All rights reserved.
//

#import "CMVVoiceOpen.h"



@implementation CMVVoiceOpen

@synthesize selected = _selected;

- (id)initWithFrame:(CGRect)frame
{
    self = [super initWithFrame:frame];
    if (self) {
        // Initialization code
    }
    _selected=TRUE;
    return self;
}
-(id)initWithCoder:(NSCoder *)aDecoder {
    self = [super initWithCoder:aDecoder];
    if(self){
        
    }
    _selected=TRUE;
    return self;
}

- (void)setSelected:(BOOL)selected
{
    if (_selected != selected) {
        _selected = selected;
        [self setNeedsDisplay];
    }
}


// Only override drawRect: if you perform custom drawing.
// An empty implementation adversely affects performance during animation.
- (void)drawRect:(CGRect)rect
{
    //// Color Declarations
    UIColor* mainColor = [UIColor colorWithRed: 1 green: 1 blue: 1 alpha: 0.783];
    
    //// Frames
    CGRect frame = rect;
    
    if (_selected) {
    //// Forma Drawing
    UIBezierPath* formaPath = [UIBezierPath bezierPath];
    [formaPath moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.04417 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76234 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.11418 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69433 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.06751 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73967 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.09085 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71700 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.07387 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53519 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.11418 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66216 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.10803 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55557 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.06179 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50974 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.06984 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52671 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.06581 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51822 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.01313 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.05443 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49135 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.01764 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41861 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.11816 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.01934 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23934 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.01920 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12971 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.26696 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.16567 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03394 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.26696 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02000 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55043 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08225 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44266 * CGRectGetWidth(frame), CGRectGetMinY(frame) + -0.00601 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.46494 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08225 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55398 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09991 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.55161 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08814 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55280 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09402 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.53392 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.54759 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11435 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.54031 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12555 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59956 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.56356 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17404 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.59105 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25233 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61269 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59951 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34098 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61269 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37191 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59334 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43382 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60700 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40503 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.59903 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41879 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64770 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59903 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44057 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.64770 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53257 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64333 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64747 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54826 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.64356 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56174 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60394 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.63082 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57070 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61836 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57478 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60832 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59847 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58903 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60832 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60887 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.53392 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59711 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62881 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.54031 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63048 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.58643 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.52857 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64797 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.58441 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65776 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59956 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59306 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66733 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60501 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67157 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.58206 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.70500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59553 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69494 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.58974 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69093 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.58643 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.58310 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71180 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.58566 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71042 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41342 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76818 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.57743 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81184 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.47100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76818 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36152 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91830 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39612 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81822 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.37881 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86826 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38950 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.36760 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93123 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38341 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93707 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38074 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38902 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95280 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38264 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98336 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.04738 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76192 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.20100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98474 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.07729 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87211 * CGRectGetHeight(frame))];
    [formaPath addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.04417 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76234 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.04631 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76206 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.04524 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76220 * CGRectGetHeight(frame))];
    [formaPath closePath];
    [mainColor setFill];
    [formaPath fill];
    
    
    //// Forma 2 Drawing
    UIBezierPath* forma2Path = [UIBezierPath bezierPath];
    [forma2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.90911 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38000 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.96687 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66841 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.90911 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38000 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.97301 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.48644 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.85801 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.96073 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85038 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.85801 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.99000 * CGRectGetHeight(frame))];
    [forma2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.83135 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96703 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.93354 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68628 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.83135 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.96703 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.92616 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.82980 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.88245 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39787 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.94193 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50523 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.88245 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.39787 * CGRectGetHeight(frame))];
    [forma2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.90911 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38000 * CGRectGetHeight(frame))];
    [forma2Path closePath];
    [forma2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.83135 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43105 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.87800 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66586 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.83135 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43105 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.87900 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49979 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.78692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92619 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.87104 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81989 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.78692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.92619 * CGRectGetHeight(frame))];
    [forma2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.76248 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90067 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.84690 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66841 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.76248 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.90067 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.83930 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.80722 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.80469 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44381 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.85184 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54058 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.80469 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.44381 * CGRectGetHeight(frame))];
    [forma2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.83135 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43105 * CGRectGetHeight(frame))];
    [forma2Path closePath];
    [forma2Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75359 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47699 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.78692 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67862 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.75359 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47699 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.79590 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56287 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.72027 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85983 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.77629 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78878 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.72027 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85983 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.71805 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85728 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.72027 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85983 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.71879 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85813 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.69583 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83431 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.70894 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.85214 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.69583 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83431 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75581 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67862 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.69583 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.83431 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.74118 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.78679 * CGRectGetHeight(frame))];
    [forma2Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.72693 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49230 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.76769 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58652 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.72693 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49230 * CGRectGetHeight(frame))];
    [forma2Path addLineToPoint: CGPointMake(CGRectGetMinX(frame) + 0.75359 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.47699 * CGRectGetHeight(frame))];
    [forma2Path closePath];
    [mainColor setFill];
    [forma2Path fill];
    } else {
        //// Forma 1 Drawing
        UIBezierPath* forma1Path = [UIBezierPath bezierPath];
        [forma1Path moveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.04417 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76234 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.11418 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69433 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.06751 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.73967 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.09085 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71700 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.07387 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53519 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.11418 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66216 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.10803 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.55557 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.06179 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.50974 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.06984 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.52671 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.06581 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.51822 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.01313 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.31500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.05443 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.49135 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.01764 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41861 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.11816 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.06500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.01934 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.23934 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.01920 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12971 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.26696 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.16567 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.03394 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.26696 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.02000 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55043 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08225 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.44266 * CGRectGetWidth(frame), CGRectGetMinY(frame) + -0.00601 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.46494 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08225 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.55398 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09991 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.55161 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.08814 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.55280 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.09402 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.53392 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.14000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.54759 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.11435 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.54031 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.12555 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59956 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.32000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.56356 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.17404 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.59105 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.25233 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.61042 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.38873 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59951 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.34098 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61042 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.37064 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59334 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43382 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60473 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.40376 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.59903 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.41879 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64770 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60033 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.43382 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.64770 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.53257 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.64333 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.64747 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.54826 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.64356 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.56174 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60394 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.63082 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57070 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.61836 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.57478 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.60556 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.61967 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59847 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.58903 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60556 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.60854 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59956 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.64000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60556 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.62443 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.59915 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.63294 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59956 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.60019 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.65081 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.60298 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.66090 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.57768 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.59516 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.68172 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.57481 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.67093 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.59519 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.71500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.57872 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69180 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.59441 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.69542 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.41342 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76818 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.58619 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.79684 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.47100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76818 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.36152 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.91830 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.39612 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.81822 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.37881 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.86826 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38950 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95000 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.36760 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93123 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38341 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.93707 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.38074 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.97500 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.38902 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.95280 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.38264 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98336 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.04738 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76192 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.20100 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.98474 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.07729 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.87211 * CGRectGetHeight(frame))];
        [forma1Path addCurveToPoint: CGPointMake(CGRectGetMinX(frame) + 0.04417 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76234 * CGRectGetHeight(frame)) controlPoint1: CGPointMake(CGRectGetMinX(frame) + 0.04631 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76206 * CGRectGetHeight(frame)) controlPoint2: CGPointMake(CGRectGetMinX(frame) + 0.04524 * CGRectGetWidth(frame), CGRectGetMinY(frame) + 0.76220 * CGRectGetHeight(frame))];
        [forma1Path closePath];
        [mainColor setFill];
        [forma1Path fill];
    }
}


@end
